"""Runs the FastAPI server as a managed subprocess and exercises the whole
system through it: upload -> RAG enrichment -> multiple NL questions
(including a conversational-memory follow-up) -> profiling -> dashboard.
Kept as one script so there's no reliance on shell job control for
backgrounding, which this sandbox doesn't handle reliably across calls.
"""
from __future__ import annotations

import json
import subprocess
import sys
import time
import os
import tempfile
import shutil
import requests

BASE = "http://127.0.0.1:8000/api/v1"


def wait_for_health(proc, timeout=25):
    start = time.time()
    attempt = 0
    while time.time() - start < timeout:
        attempt += 1
        if proc.poll() is not None:
            print("!! Server process exited early with code", proc.returncode)
            return False
        try:
            r = requests.get(f"{BASE}/health", timeout=2)
            if r.status_code == 200:
                print(f"Healthy on attempt {attempt} (t={time.time()-start:.1f}s)")
                return True
            print(f"attempt {attempt}: got status {r.status_code}")
        except requests.RequestException as exc:
            print(f"attempt {attempt} (t={time.time()-start:.1f}s): {type(exc).__name__}: {exc}")
        time.sleep(0.5)
    return False


def section(title):
    print("\n" + "=" * 10, title, "=" * 10)


def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    log_path = os.path.join(tempfile.gettempdir(), "uvicorn.log")
    log_file = open(log_path, "w")
    
    uvicorn_bin = "uvicorn.exe" if os.name == "nt" else "uvicorn"
    uvicorn_path = os.path.join(os.path.dirname(sys.executable), uvicorn_bin)
    
    proc = subprocess.Popen(
        [uvicorn_path, "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000"],
        stdout=log_file,
        stderr=subprocess.STDOUT,
        cwd=base_dir,
    )

    try:
        if not wait_for_health(proc, timeout=90):
            log_file.flush()
            print("Server never became healthy. Log:")
            try:
                print(open(log_path).read())
            except Exception as e:
                print("Failed to read log:", e)
            sys.exit(1)
        print("Server healthy.")

        section("UPLOAD")
        csv_path = os.path.join(base_dir, "examples", "orders_demo.csv")
        with open(csv_path, "rb") as f:
            r = requests.post(f"{BASE}/datasets/upload", files={"file": ("orders_demo.csv", f, "text/csv")})
        r.raise_for_status()
        dataset = r.json()
        print(json.dumps(dataset, indent=2, default=str))
        dataset_id = dataset["id"]

        section("ENRICH BUSINESS GLOSSARY: total_price")
        r = requests.patch(
            f"{BASE}/datasets/{dataset_id}/columns/total_price",
            json={"description": "Final price after discount. Represents the sale revenue generated by this order line."},
        )
        r.raise_for_status()
        print("Saved OK.")

        section("Q1: What is the total revenue?")
        r = requests.post(f"{BASE}/chat/ask", json={"question": "What is the total revenue?"})
        r.raise_for_status()
        d = r.json()
        print("SQL:\n", d["sql"])
        print("Explanation:", d["explanation"])
        print("plotly_figure present:", d["plotly_figure"] is not None)

        section("Q2: Which product had the highest total sales in June?")
        r = requests.post(f"{BASE}/chat/ask", json={"question": "Which product had the highest total sales in June?"})
        r.raise_for_status()
        d = r.json()
        print("SQL:\n", d["sql"])
        print("Explanation:", d["explanation"])
        print("Rows:", d["rows"])

        section("Q3: Show top 5 customers by revenue")
        r = requests.post(f"{BASE}/chat/ask", json={"question": "Show top 5 customers by revenue"})
        r.raise_for_status()
        d = r.json()
        print("SQL:\n", d["sql"])
        print("Row count:", d["row_count"])
        print("Explanation:", d["explanation"])

        section("Q4a: Show total sales by product (starts a conversation)")
        r = requests.post(f"{BASE}/chat/ask", json={"question": "Show total sales by product"})
        r.raise_for_status()
        d4a = r.json()
        conv_id = d4a["conversation_id"]
        print("SQL:\n", d4a["sql"])
        print("conversation_id:", conv_id)

        section("Q4b: Only Electronics  <-- conversational memory + filter-vs-dimension test")
        r = requests.post(f"{BASE}/chat/ask", json={"question": "Only Electronics", "conversation_id": conv_id})
        r.raise_for_status()
        d4b = r.json()
        print("resolved_question:", d4b["resolved_question"])
        print("SQL:\n", d4b["sql"])
        print("Explanation:", d4b["explanation"])

        section("PROFILE")
        r = requests.get(f"{BASE}/datasets/{dataset_id}/profile")
        r.raise_for_status()
        profile = r.json()["profile"]
        print("row_count:", profile["row_count"], "column_count:", profile["column_count"], "duplicate_rows:", profile["duplicate_rows"])
        print("total_price stats:", json.dumps(profile["columns"]["total_price"], indent=2))

        section("DASHBOARD")
        r = requests.get(f"{BASE}/datasets/{dataset_id}/dashboard")
        r.raise_for_status()
        dash = r.json()
        print("KPI cards:", dash["kpi_cards"])
        print("num charts:", len(dash["charts"]))
        if dash["charts"]:
            print("first chart has plotly_figure:", dash["charts"][0]["plotly_figure"] is not None)

        section("DATASETS LIST")
        r = requests.get(f"{BASE}/datasets")
        r.raise_for_status()
        print(json.dumps(r.json(), indent=2, default=str))

        section("ALL DEMO STEPS COMPLETED SUCCESSFULLY")

    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()
        log_file.close()
        try:
            print("\n--- uvicorn.log ---")
            print(open(log_path).read()[:10000]) # limit output in case it is too long
        except Exception:
            pass


if __name__ == "__main__":
    main()

